QT       += core gui serialport network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    addtargetdialog.cpp \
    generic_port.cpp \
    main.cpp \
    kgroundcontrol.cpp \
    serial_port.cpp \
    settings.cpp \
    target_thread.cpp

HEADERS += \
    addtargetdialog.h \
    generic_port.h \
    kgroundcontrol.h \
    libs/Mavlink/mavlink2/ASLUAV/ASLUAV.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_asl_obctrl.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_aslctrl_data.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_aslctrl_debug.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_asluav_status.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_command_int_stamped.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_command_long_stamped.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_ekf_ext.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_fw_soaring_data.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_gsm_link_status.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_satcom_link_status.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sens_atmos.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sens_batmon.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sens_mppt.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sens_power.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sens_power_board.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sensor_airflow_angles.h \
    libs/Mavlink/mavlink2/ASLUAV/mavlink_msg_sensorpod_status.h \
    libs/Mavlink/mavlink2/ASLUAV/testsuite.h \
    libs/Mavlink/mavlink2/ASLUAV/version.h \
    libs/Mavlink/mavlink2/ardupilotmega/ardupilotmega.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_adap_tuning.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_ahrs.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_ahrs2.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_ahrs3.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_aoa_ssa.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_ap_adc.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_battery2.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_camera_feedback.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_camera_status.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_compassmot_status.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_data16.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_data32.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_data64.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_data96.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_deepstall.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_device_op_read.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_device_op_write.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_digicam_configure.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_digicam_control.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_ekf_status_report.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_esc_telemetry_1_to_4.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_esc_telemetry_5_to_8.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_esc_telemetry_9_to_12.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_fence_point.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gimbal_control.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gimbal_report.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gopro_get_request.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gopro_get_response.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gopro_set_request.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_gopro_set_response.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_hwstatus.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_led_control.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_limits_status.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_mcu_status.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_meminfo.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_mount_configure.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_mount_control.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_mount_status.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_obstacle_distance_3d.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_osd_param_config.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_osd_param_config_reply.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_osd_param_show_config.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_osd_param_show_config_reply.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_pid_tuning.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_radio.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_rally_point.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_rangefinder.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_rpm.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_sensor_offsets.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_simstate.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_vision_position_delta.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_water_depth.h \
    libs/Mavlink/mavlink2/ardupilotmega/mavlink_msg_wind.h \
    libs/Mavlink/mavlink2/ardupilotmega/testsuite.h \
    libs/Mavlink/mavlink2/ardupilotmega/version.h \
    libs/Mavlink/mavlink2/checksum.h \
    libs/Mavlink/mavlink2/common/common.h \
    libs/Mavlink/mavlink2/common/mavlink.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_actuator_control_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_actuator_output_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_adsb_vehicle.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_ais_vessel.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_altitude.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_att_pos_mocap.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_attitude.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_attitude_quaternion.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_attitude_quaternion_cov.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_attitude_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_auth_key.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_autopilot_version.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_battery_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_button_change.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_capture_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_fov_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_image_captured.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_settings.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_tracking_geo_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_tracking_image_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_camera_trigger.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_can_filter_modify.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_can_frame.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_canfd_frame.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_cellular_config.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_cellular_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_change_operator_control.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_change_operator_control_ack.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_collision.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_command_ack.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_command_cancel.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_command_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_command_long.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_component_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_component_metadata.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_control_system_state.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_current_event_sequence.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_data_stream.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_data_transmission_handshake.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_debug.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_debug_float_array.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_debug_vect.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_distance_sensor.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_efi_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_encapsulated_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_esc_info.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_esc_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_estimator_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_event.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_extended_sys_state.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_fence_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_file_transfer_protocol.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_flight_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_follow_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_generator_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_device_attitude_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_device_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_device_set_attitude.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_manager_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_manager_set_attitude.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_manager_set_manual_control.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gimbal_manager_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_global_position_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_global_position_int_cov.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_global_vision_position_estimate.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps2_raw.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps2_rtk.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_global_origin.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_inject_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_input.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_raw_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_rtcm_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_rtk.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_gps_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_high_latency.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_high_latency2.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_highres_imu.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_actuator_controls.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_controls.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_gps.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_optical_flow.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_rc_inputs_raw.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_sensor.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_state.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hil_state_quaternion.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_home_position.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_hygrometer_sensor.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_isbd_link_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_landing_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_link_node_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_local_position_ned.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_local_position_ned_cov.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_local_position_ned_system_global_offset.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_log_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_log_entry.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_log_erase.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_log_request_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_log_request_end.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_log_request_list.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_logging_ack.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_logging_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_logging_data_acked.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mag_cal_report.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_manual_control.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_manual_setpoint.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_memory_vect.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_message_interval.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_ack.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_clear_all.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_count.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_current.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_item.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_item_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_item_reached.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_request.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_request_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_request_list.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_request_partial_list.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_set_current.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mission_write_partial_list.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_mount_orientation.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_named_value_float.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_named_value_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_nav_controller_output.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_obstacle_distance.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_odometry.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_onboard_computer_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_arm_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_authentication.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_basic_id.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_location.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_message_pack.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_operator_id.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_self_id.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_system.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_open_drone_id_system_update.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_optical_flow.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_optical_flow_rad.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_orbit_execution_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_ext_ack.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_ext_request_list.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_ext_request_read.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_ext_set.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_ext_value.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_map_rc.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_request_list.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_request_read.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_set.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_param_value.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_ping.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_play_tune.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_play_tune_v2.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_position_target_global_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_position_target_local_ned.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_power_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_radio_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_raw_imu.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_raw_pressure.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_raw_rpm.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_rc_channels.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_rc_channels_override.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_rc_channels_raw.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_rc_channels_scaled.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_request_data_stream.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_request_event.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_resource_request.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_response_event_error.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_safety_allowed_area.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_safety_set_allowed_area.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_scaled_imu.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_scaled_imu2.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_scaled_imu3.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_scaled_pressure.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_scaled_pressure2.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_scaled_pressure3.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_serial_control.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_servo_output_raw.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_actuator_control_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_attitude_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_gps_global_origin.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_home_position.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_mode.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_position_target_global_int.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_set_position_target_local_ned.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_setup_signing.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_sim_state.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_smart_battery_info.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_statustext.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_storage_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_supported_tunes.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_sys_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_system_time.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_terrain_check.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_terrain_data.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_terrain_report.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_terrain_request.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_time_estimate_to_target.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_timesync.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_trajectory_representation_bezier.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_trajectory_representation_waypoints.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_tunnel.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_uavcan_node_info.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_uavcan_node_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_utm_global_position.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_v2_extension.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_vfr_hud.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_vibration.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_vicon_position_estimate.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_video_stream_information.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_video_stream_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_vision_position_estimate.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_vision_speed_estimate.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_wheel_distance.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_wifi_config_ap.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_winch_status.h \
    libs/Mavlink/mavlink2/common/mavlink_msg_wind_cov.h \
    libs/Mavlink/mavlink2/common/testsuite.h \
    libs/Mavlink/mavlink2/common/version.h \
    libs/Mavlink/mavlink2/csAirLink/csAirLink.h \
    libs/Mavlink/mavlink2/csAirLink/mavlink.h \
    libs/Mavlink/mavlink2/csAirLink/mavlink_msg_airlink_auth.h \
    libs/Mavlink/mavlink2/csAirLink/mavlink_msg_airlink_auth_response.h \
    libs/Mavlink/mavlink2/csAirLink/testsuite.h \
    libs/Mavlink/mavlink2/csAirLink/version.h \
    libs/Mavlink/mavlink2/cubepilot/cubepilot.h \
    libs/Mavlink/mavlink2/cubepilot/mavlink.h \
    libs/Mavlink/mavlink2/cubepilot/mavlink_msg_cubepilot_firmware_update_resp.h \
    libs/Mavlink/mavlink2/cubepilot/mavlink_msg_cubepilot_firmware_update_start.h \
    libs/Mavlink/mavlink2/cubepilot/mavlink_msg_cubepilot_raw_rc.h \
    libs/Mavlink/mavlink2/cubepilot/mavlink_msg_herelink_telem.h \
    libs/Mavlink/mavlink2/cubepilot/mavlink_msg_herelink_video_stream_information.h \
    libs/Mavlink/mavlink2/cubepilot/testsuite.h \
    libs/Mavlink/mavlink2/cubepilot/version.h \
    libs/Mavlink/mavlink2/development/development.h \
    libs/Mavlink/mavlink2/development/mavlink.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_airspeed.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_available_modes.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_battery_status_v2.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_component_information_basic.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_current_mode.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_figure_eight_execution_status.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_group_end.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_group_start.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_mission_checksum.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_param_ack_transaction.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_target_absolute.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_target_relative.h \
    libs/Mavlink/mavlink2/development/mavlink_msg_wifi_network_info.h \
    libs/Mavlink/mavlink2/development/testsuite.h \
    libs/Mavlink/mavlink2/development/version.h \
    libs/Mavlink/mavlink2/icarous/icarous.h \
    libs/Mavlink/mavlink2/icarous/mavlink.h \
    libs/Mavlink/mavlink2/icarous/mavlink_msg_icarous_heartbeat.h \
    libs/Mavlink/mavlink2/icarous/mavlink_msg_icarous_kinematic_bands.h \
    libs/Mavlink/mavlink2/icarous/testsuite.h \
    libs/Mavlink/mavlink2/icarous/version.h \
    libs/Mavlink/mavlink2/matrixpilot/matrixpilot.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_airspeeds.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_altitudes.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_command.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_directory.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_flexifunction_set.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    libs/Mavlink/mavlink2/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    libs/Mavlink/mavlink2/matrixpilot/testsuite.h \
    libs/Mavlink/mavlink2/matrixpilot/version.h \
    libs/Mavlink/mavlink2/mavlink_conversions.h \
    libs/Mavlink/mavlink2/mavlink_get_info.h \
    libs/Mavlink/mavlink2/mavlink_helpers.h \
    libs/Mavlink/mavlink2/mavlink_sha256.h \
    libs/Mavlink/mavlink2/mavlink_types.h \
    libs/Mavlink/mavlink2/minimal/mavlink.h \
    libs/Mavlink/mavlink2/minimal/mavlink_msg_heartbeat.h \
    libs/Mavlink/mavlink2/minimal/mavlink_msg_protocol_version.h \
    libs/Mavlink/mavlink2/minimal/minimal.h \
    libs/Mavlink/mavlink2/minimal/testsuite.h \
    libs/Mavlink/mavlink2/minimal/version.h \
    libs/Mavlink/mavlink2/protocol.h \
    libs/Mavlink/mavlink2/standard/mavlink.h \
    libs/Mavlink/mavlink2/standard/standard.h \
    libs/Mavlink/mavlink2/standard/testsuite.h \
    libs/Mavlink/mavlink2/standard/version.h \
    libs/Mavlink/mavlink2/test/mavlink.h \
    libs/Mavlink/mavlink2/test/mavlink_msg_test_types.h \
    libs/Mavlink/mavlink2/test/test.h \
    libs/Mavlink/mavlink2/test/testsuite.h \
    libs/Mavlink/mavlink2/test/version.h \
    libs/Mavlink/mavlink2/uAvionix/mavlink.h \
    libs/Mavlink/mavlink2/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    libs/Mavlink/mavlink2/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    libs/Mavlink/mavlink2/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    libs/Mavlink/mavlink2/uAvionix/testsuite.h \
    libs/Mavlink/mavlink2/uAvionix/uAvionix.h \
    libs/Mavlink/mavlink2/uAvionix/version.h \
    serial_port.h \
    settings.h \
    target_thread.h

FORMS += \
    addtargetdialog.ui \
    kgroundcontrol.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    libs/Mavlink/mavlink2/message_definitions/ASLUAV.xml \
    libs/Mavlink/mavlink2/message_definitions/AVSSUAS.xml \
    libs/Mavlink/mavlink2/message_definitions/all.xml \
    libs/Mavlink/mavlink2/message_definitions/ardupilotmega.xml \
    libs/Mavlink/mavlink2/message_definitions/common.xml \
    libs/Mavlink/mavlink2/message_definitions/csAirLink.xml \
    libs/Mavlink/mavlink2/message_definitions/cubepilot.xml \
    libs/Mavlink/mavlink2/message_definitions/development.xml \
    libs/Mavlink/mavlink2/message_definitions/icarous.xml \
    libs/Mavlink/mavlink2/message_definitions/matrixpilot.xml \
    libs/Mavlink/mavlink2/message_definitions/minimal.xml \
    libs/Mavlink/mavlink2/message_definitions/paparazzi.xml \
    libs/Mavlink/mavlink2/message_definitions/python_array_test.xml \
    libs/Mavlink/mavlink2/message_definitions/standard.xml \
    libs/Mavlink/mavlink2/message_definitions/storm32.xml \
    libs/Mavlink/mavlink2/message_definitions/test.xml \
    libs/Mavlink/mavlink2/message_definitions/uAvionix.xml \
    libs/Mavlink/mavlink2/message_definitions/ualberta.xml
